name: integration-tests

defaults:
  run:
    working-directory: .

on:
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: .
      - name: Build containers
        run: docker-compose -f docker-compose.yml build
      - name: Run containers
        run: docker-compose up -f docker-compose.yml --detach
      - name: Migrate
        run: docker-compose run worker cargo run --bin migrate
      - name: Run tests
        run: docker-compose run worker cargo test
      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml down
