name: integration-tests

defaults:
  run:
    working-directory: .

on:
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: .
      - name: Build containers
        run: docker-compose build
      - name: Run containers
        run: docker-compose up -d
      - name: Wait
        run: sleep 5
      - name: Migrate
        run: docker exec -it rust-queue-worker sh -c "cargo run --bin migrate"
      - name: Run tests
        run: docker exec -it rust-queue-worker sh -c "cargo test"
      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml down
